const products = [
  {
    product_id: 1,
    name: "Muffin Chocolate Individual Wrap",
    description: "Pork - Tenderloin, Frozen",
    category: "Comedy|Drama|Romance",
    image: "http://dummyimage.com/180x100.png/cc0000/ffffff",
    buyingPrice: "$48.67",
    retailPrice: "$8.85",
    barcode: "55154-5980",
    supplier_id: 98,
  },
  {
    product_id: 2,
    name: "Longos - Greek Salad",
    description: "Wild Boar - Tenderloin",
    category: "Drama|Romance",
    image: "http://dummyimage.com/246x100.png/dddddd/000000",
    buyingPrice: "$37.82",
    retailPrice: "$11.55",
    barcode: "51824-022",
    supplier_id: 24,
  },
  {
    product_id: 3,
    name: "Wine - Guy Sage Touraine",
    description: "Wine - Sauvignon Blanc Oyster",
    category: "Drama|Thriller|War",
    image: "http://dummyimage.com/174x100.png/dddddd/000000",
    buyingPrice: "$24.08",
    retailPrice: "$13.25",
    barcode: "54575-228",
    supplier_id: 47,
  },
  {
    product_id: 4,
    name: "Oil - Coconut",
    description: "Pie Shell - 9",
    category: "Drama|Sci-Fi",
    image: "http://dummyimage.com/242x100.png/cc0000/ffffff",
    buyingPrice: "$20.87",
    retailPrice: "$4.96",
    barcode: "50881-020",
    supplier_id: 94,
  },
  {
    product_id: 5,
    name: "Lemon Tarts",
    description: "Sauce - Oyster",
    category: "Drama",
    image: "http://dummyimage.com/222x100.png/ff4444/ffffff",
    buyingPrice: "$14.20",
    retailPrice: "$0.02",
    barcode: "0168-0353",
    supplier_id: 71,
  },
  {
    product_id: 6,
    name: "Sea Bass - Whole",
    description: "Cheese - Roquefort Pappillon",
    category: "Action|Comedy|Crime|Thriller",
    image: "http://dummyimage.com/194x100.png/5fa2dd/ffffff",
    buyingPrice: "$23.41",
    retailPrice: "$3.13",
    barcode: "63739-800",
    supplier_id: 74,
  },
  {
    product_id: 7,
    name: "Tea - Decaf 1 Cup",
    description: "Black Currants",
    category: "Drama",
    image: "http://dummyimage.com/220x100.png/cc0000/ffffff",
    buyingPrice: "$22.49",
    retailPrice: "$3.25",
    barcode: "67777-235",
    supplier_id: 69,
  },
  {
    product_id: 8,
    name: "Wine - Ej Gallo Sonoma",
    description: "Cheese - Perron Cheddar",
    category: "Comedy|Drama|Musical|Mystery",
    image: "http://dummyimage.com/143x100.png/dddddd/000000",
    buyingPrice: "$30.56",
    retailPrice: "$33.08",
    barcode: "13734-130",
    supplier_id: 94,
  },
  {
    product_id: 9,
    name: "Pasta - Canelloni, Single Serve",
    description: "Chicken - Wieners",
    category: "Adventure|Documentary",
    image: "http://dummyimage.com/135x100.png/ff4444/ffffff",
    buyingPrice: "$25.99",
    retailPrice: "$0.55",
    barcode: "56062-434",
    supplier_id: 55,
  },
  {
    product_id: 10,
    name: "Celery Root",
    description: "Hipnotiq Liquor",
    category: "Sci-Fi",
    image: "http://dummyimage.com/140x100.png/dddddd/000000",
    buyingPrice: "$19.75",
    retailPrice: "$9.22",
    barcode: "62670-4359",
    supplier_id: 29,
  },
  {
    product_id: 11,
    name: "Soup - Cream Of Broccoli",
    description: "Pears - Bosc",
    category: "Action|Comedy|Crime",
    image: "http://dummyimage.com/122x100.png/ff4444/ffffff",
    buyingPrice: "$20.40",
    retailPrice: "$19.36",
    barcode: "57955-5159",
    supplier_id: 27,
  },
  {
    product_id: 12,
    name: "Cake - French Pear Tart",
    description: "Cheese - Brie, Triple Creme",
    category: "Drama",
    image: "http://dummyimage.com/108x100.png/5fa2dd/ffffff",
    buyingPrice: "$17.94",
    retailPrice: "$34.38",
    barcode: "17518-054",
    supplier_id: 38,
  },
  {
    product_id: 13,
    name: "Chocolate - Pistoles, Lactee, Milk",
    description: "Dates",
    category: "Action|Drama|Fantasy",
    image: "http://dummyimage.com/193x100.png/dddddd/000000",
    buyingPrice: "$3.38",
    retailPrice: "$23.67",
    barcode: "0615-7555",
    supplier_id: 67,
  },
  {
    product_id: 14,
    name: "Cherries - Bing, Canned",
    description: "Flour - So Mix Cake White",
    category: "Comedy|Drama",
    image: "http://dummyimage.com/242x100.png/ff4444/ffffff",
    buyingPrice: "$34.16",
    retailPrice: "$31.62",
    barcode: "49349-119",
    supplier_id: 100,
  },
  {
    product_id: 15,
    name: "Sauce - White, Mix",
    description: "Olives - Black, Pitted",
    category: "Drama",
    image: "http://dummyimage.com/189x100.png/dddddd/000000",
    buyingPrice: "$41.63",
    retailPrice: "$27.65",
    barcode: "24653-801",
    supplier_id: 64,
  },
  {
    product_id: 16,
    name: "Pear - Halves",
    description: "Artichokes - Knobless, White",
    category: "Documentary",
    image: "http://dummyimage.com/227x100.png/ff4444/ffffff",
    buyingPrice: "$38.79",
    retailPrice: "$11.28",
    barcode: "52033-001",
    supplier_id: 26,
  },
  {
    product_id: 17,
    name: "Snapple Lemon Tea",
    description: "Rum - Cream, Amarula",
    category: "Drama",
    image: "http://dummyimage.com/104x100.png/dddddd/000000",
    buyingPrice: "$48.08",
    retailPrice: "$29.68",
    barcode: "65044-5049",
    supplier_id: 45,
  },
  {
    product_id: 18,
    name: "Venison - Denver Leg Boneless",
    description: "Cakes Assorted",
    category: "Comedy|Drama",
    image: "http://dummyimage.com/100x100.png/cc0000/ffffff",
    buyingPrice: "$24.85",
    retailPrice: "$29.51",
    barcode: "55154-1610",
    supplier_id: 85,
  },
  {
    product_id: 19,
    name: "Hold Up Tool Storage Rack",
    description: "Pepper - Cayenne",
    category: "Drama",
    image: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
    buyingPrice: "$8.53",
    retailPrice: "$4.92",
    barcode: "0054-3194",
    supplier_id: 51,
  },
  {
    product_id: 20,
    name: "Beef - Rib Roast, Capless",
    description: "Wine - Niagara Peninsula Vqa",
    category: "Documentary|Musical",
    image: "http://dummyimage.com/216x100.png/cc0000/ffffff",
    buyingPrice: "$29.53",
    retailPrice: "$49.83",
    barcode: "59779-908",
    supplier_id: 88,
  },
  {
    product_id: 21,
    name: "Ice Cream Bar - Oreo Sandwich",
    description: "Wine - Cava Aria Estate Brut",
    category: "Drama|Musical",
    image: "http://dummyimage.com/213x100.png/dddddd/000000",
    buyingPrice: "$35.20",
    retailPrice: "$2.32",
    barcode: "58232-4001",
    supplier_id: 94,
  },
  {
    product_id: 22,
    name: "Wine - Rosso Del Veronese Igt",
    description: "Wine - Red, Gamay Noir",
    category: "Comedy|Drama",
    image: "http://dummyimage.com/240x100.png/ff4444/ffffff",
    buyingPrice: "$3.76",
    retailPrice: "$0.33",
    barcode: "66382-299",
    supplier_id: 90,
  },
  {
    product_id: 23,
    name: "Swiss Chard",
    description: "Russian Prince",
    category: "Drama",
    image: "http://dummyimage.com/128x100.png/ff4444/ffffff",
    buyingPrice: "$6.47",
    retailPrice: "$30.59",
    barcode: "0781-1832",
    supplier_id: 22,
  },
  {
    product_id: 24,
    name: "Apple - Northern Spy",
    description: "Sun - Dried Tomatoes",
    category: "Drama|War",
    image: "http://dummyimage.com/248x100.png/cc0000/ffffff",
    buyingPrice: "$20.31",
    retailPrice: "$48.53",
    barcode: "0781-5618",
    supplier_id: 2,
  },
  {
    product_id: 25,
    name: "Onions - Cippolini",
    description: "Cheese - Manchego, Spanish",
    category: "Drama",
    image: "http://dummyimage.com/238x100.png/cc0000/ffffff",
    buyingPrice: "$49.09",
    retailPrice: "$49.84",
    barcode: "65862-156",
    supplier_id: 28,
  },
  {
    product_id: 26,
    name: "Appetizer - Tarragon Chicken",
    description: "Beef - Sushi Flat Iron Steak",
    category: "Western",
    image: "http://dummyimage.com/196x100.png/ff4444/ffffff",
    buyingPrice: "$26.81",
    retailPrice: "$39.47",
    barcode: "43538-600",
    supplier_id: 27,
  },
  {
    product_id: 27,
    name: "Ham - Procutinni",
    description: "Veal - Leg",
    category: "Drama",
    image: "http://dummyimage.com/169x100.png/cc0000/ffffff",
    buyingPrice: "$6.91",
    retailPrice: "$0.50",
    barcode: "50988-198",
    supplier_id: 70,
  },
  {
    product_id: 28,
    name: "Pepper - Red, Finger Hot",
    description: "Fruit Salad Deluxe",
    category: "Horror",
    image: "http://dummyimage.com/142x100.png/dddddd/000000",
    buyingPrice: "$46.80",
    retailPrice: "$12.56",
    barcode: "59478-000",
    supplier_id: 92,
  },
  {
    product_id: 29,
    name: "Soup - Campbells, Cream Of",
    description: "Oil - Pumpkinseed",
    category: "Crime|Drama|Romance",
    image: "http://dummyimage.com/116x100.png/cc0000/ffffff",
    buyingPrice: "$43.54",
    retailPrice: "$24.24",
    barcode: "54868-4992",
    supplier_id: 49,
  },
  {
    product_id: 30,
    name: "Fond - Neutral",
    description: "Langers - Cranberry Cocktail",
    category: "Thriller",
    image: "http://dummyimage.com/218x100.png/5fa2dd/ffffff",
    buyingPrice: "$20.27",
    retailPrice: "$44.85",
    barcode: "68752-034",
    supplier_id: 73,
  },
  {
    product_id: 31,
    name: "Rye Special Old",
    description: "Cocktail Napkin Blue",
    category: "Documentary",
    image: "http://dummyimage.com/154x100.png/5fa2dd/ffffff",
    buyingPrice: "$17.03",
    retailPrice: "$32.22",
    barcode: "50436-6462",
    supplier_id: 20,
  },
  {
    product_id: 32,
    name: "Wine - Jafflin Bourgongone",
    description: "Jam - Blackberry, 20 Ml Jar",
    category: "Drama|Mystery",
    image: "http://dummyimage.com/163x100.png/ff4444/ffffff",
    buyingPrice: "$28.90",
    retailPrice: "$41.35",
    barcode: "0574-0815",
    supplier_id: 33,
  },
  {
    product_id: 33,
    name: "Sugar - Invert",
    description: "Pasta - Cheese / Spinach Bauletti",
    category: "Comedy|Musical",
    image: "http://dummyimage.com/194x100.png/dddddd/000000",
    buyingPrice: "$46.05",
    retailPrice: "$28.17",
    barcode: "0781-5608",
    supplier_id: 92,
  },
  {
    product_id: 34,
    name: "Duck - Fat",
    description: "Flavouring - Raspberry",
    category: "Comedy|Romance",
    image: "http://dummyimage.com/249x100.png/dddddd/000000",
    buyingPrice: "$7.03",
    retailPrice: "$49.74",
    barcode: "0268-1126",
    supplier_id: 75,
  },
  {
    product_id: 35,
    name: "Steamers White",
    description: "Wine - White Cab Sauv.on",
    category: "Drama",
    image: "http://dummyimage.com/168x100.png/5fa2dd/ffffff",
    buyingPrice: "$49.93",
    retailPrice: "$47.48",
    barcode: "57520-0292",
    supplier_id: 85,
  },
  {
    product_id: 36,
    name: "Stock - Beef, White",
    description: "Cake - Dulce De Leche",
    category: "Action|Adventure|Animation|Children",
    image: "http://dummyimage.com/167x100.png/cc0000/ffffff",
    buyingPrice: "$0.00",
    retailPrice: "$20.61",
    barcode: "35378-0006",
    supplier_id: 3,
  },
  {
    product_id: 37,
    name: "Jolt Cola - Red Eye",
    description: "Garbag Bags - Black",
    category: "Drama",
    image: "http://dummyimage.com/193x100.png/5fa2dd/ffffff",
    buyingPrice: "$11.42",
    retailPrice: "$14.61",
    barcode: "0781-1375",
    supplier_id: 88,
  },
  {
    product_id: 38,
    name: "Chocolate - Compound Coating",
    description: "Blueberries",
    category: "Drama",
    image: "http://dummyimage.com/151x100.png/cc0000/ffffff",
    buyingPrice: "$20.46",
    retailPrice: "$29.87",
    barcode: "62296-0023",
    supplier_id: 68,
  },
  {
    product_id: 39,
    name: "Cheese - Cheddarsliced",
    description: "Veal - Shank, Pieces",
    category: "Drama",
    image: "http://dummyimage.com/147x100.png/dddddd/000000",
    buyingPrice: "$37.35",
    retailPrice: "$41.16",
    barcode: "75930-001",
    supplier_id: 44,
  },
  {
    product_id: 40,
    name: "Onions - Cooking",
    description: "Lettuce Romaine Chopped",
    category: "Comedy|Drama|Romance",
    image: "http://dummyimage.com/210x100.png/cc0000/ffffff",
    buyingPrice: "$35.62",
    retailPrice: "$13.30",
    barcode: "50419-254",
    supplier_id: 9,
  },
  {
    product_id: 41,
    name: "Calaloo",
    description: "Lemons",
    category: "Horror|Sci-Fi",
    image: "http://dummyimage.com/220x100.png/dddddd/000000",
    buyingPrice: "$20.89",
    retailPrice: "$20.55",
    barcode: "63739-375",
    supplier_id: 74,
  },
  {
    product_id: 42,
    name: "Lemon Tarts",
    description: "Pate Pans Yellow",
    category: "Drama|Romance",
    image: "http://dummyimage.com/208x100.png/cc0000/ffffff",
    buyingPrice: "$18.00",
    retailPrice: "$8.81",
    barcode: "63629-3380",
    supplier_id: 10,
  },
  {
    product_id: 43,
    name: "Pasta - Cannelloni, Sheets, Fresh",
    description: "Chocolate - Mi - Amere Semi",
    category: "Action|Adventure|Romance|Thriller",
    image: "http://dummyimage.com/159x100.png/dddddd/000000",
    buyingPrice: "$33.56",
    retailPrice: "$27.75",
    barcode: "0067-8114",
    supplier_id: 66,
  },
  {
    product_id: 44,
    name: "Bagel - Whole White Sesame",
    description: "Sour Puss - Tangerine",
    category: "Comedy|Drama|Musical",
    image: "http://dummyimage.com/161x100.png/ff4444/ffffff",
    buyingPrice: "$48.31",
    retailPrice: "$13.60",
    barcode: "0363-5336",
    supplier_id: 3,
  },
  {
    product_id: 45,
    name: "Sobe - Lizard Fuel",
    description: "Cabbage - Savoy",
    category: "Comedy",
    image: "http://dummyimage.com/150x100.png/cc0000/ffffff",
    buyingPrice: "$18.91",
    retailPrice: "$38.56",
    barcode: "49580-1108",
    supplier_id: 44,
  },
  {
    product_id: 46,
    name: "Oxtail - Cut",
    description: "Spring Roll Veg Mini",
    category: "Drama|Romance",
    image: "http://dummyimage.com/246x100.png/cc0000/ffffff",
    buyingPrice: "$49.32",
    retailPrice: "$48.07",
    barcode: "43406-0071",
    supplier_id: 29,
  },
  {
    product_id: 47,
    name: "Mushroom - Enoki, Dry",
    description: "Wine - Red, Pinot Noir, Chateau",
    category: "Drama",
    image: "http://dummyimage.com/160x100.png/5fa2dd/ffffff",
    buyingPrice: "$40.09",
    retailPrice: "$41.33",
    barcode: "0603-3442",
    supplier_id: 70,
  },
  {
    product_id: 48,
    name: "Beef - Ox Tongue",
    description: "Boogies",
    category: "Drama|Horror|Thriller",
    image: "http://dummyimage.com/205x100.png/ff4444/ffffff",
    buyingPrice: "$12.32",
    retailPrice: "$3.32",
    barcode: "60793-434",
    supplier_id: 10,
  },
  {
    product_id: 49,
    name: "Bread - Rolls, Rye",
    description: "Energy - Boo - Koo",
    category: "Children|Comedy|Drama",
    image: "http://dummyimage.com/203x100.png/cc0000/ffffff",
    buyingPrice: "$13.76",
    retailPrice: "$17.00",
    barcode: "67046-031",
    supplier_id: 18,
  },
  {
    product_id: 50,
    name: "Propel Sport Drink",
    description: "Cheese - Mozzarella, Buffalo",
    category: "Drama|Film-Noir|Thriller",
    image: "http://dummyimage.com/118x100.png/cc0000/ffffff",
    buyingPrice: "$14.84",
    retailPrice: "$10.01",
    barcode: "57844-716",
    supplier_id: 77,
  },
];

export function getProducts() {
  return products;
}

export function getProduct(id) {
  return products.find((c) => c.product_id === id);
}

export function saveProduct(product) {
  let productInDb =
    products.find((c) => c.product_id === product.product_id) || {};
  productInDb.name = product.name;
  productInDb.description = product.description;
  productInDb.category = product.category;
  productInDb.buyingPrice = product.buyingPrice;
  productInDb.retailPrice = product.retailPrice;
  productInDb.barcode = product.barcode;
  productInDb.supplier_id = product.supplier_id;

  if (!productInDb.product_id) {
    productInDb.product_id = products.length + 1;
    products.push(productInDb);
  }

  return productInDb;
}
